### ISSUE TITLE
Security concern

### ISSUE THREAD

**Issue by saleem-hadad** [Ahid-Naif/E-Mail-Box#1]
Please don't version control any sensitive information like here
https://github.com/Ahid-Naif/E-Mail-Box/blob/cfa90ab91fc252f78335fe7120fb42bd7aaf42f7/app/helpers.php#L36

**Comment by saleem-hadad** [comment]
@Ahid-Naif

**Comment by Ahid-Naif** [comment]
Sure. Thanks for the notice!
